apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: k72pb76nz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k72pb76nz-python 
  name: k72pb76nz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: k72pb76nz-python 
